### ISSUE TITLE
Tunnistus migration configuration changes

### ISSUE THREAD

**Issue by sirtawast** [City-of-Helsinki/yjdh#3088]
## Tunnistamo -> Tunnistus migration

Listing all the necessary changes to envs when going 100% Tunnistus.

### TODO:

1. Prepare release
2. Change public env vars
3. Change private env vars
4. Build & test on stage
5. Build & test on production

### Public vars (dev.azure.com / Library)

Changes to following:

- [x] GDPR_API_DELETE_SCOPE
- [x] GDPR_API_QUERY_SCOPE
- [x] HELSINKI_PROFILE_SCOPE
- [x] OIDC_OP_BASE_URL
- [x] ~OIDC_OP_LOGOUT_CALLBACK_URL~
- [x] TOKEN_AUTH_ACCEPTED_AUDIENCE

Can be removed safely:

- [ ] SOCIAL_AUTH_TUNNISTAMO_KEY
- [ ] SOCIAL_AUTH_TUNNISTAMO_OIDC_ENDPOINT
- [ ] SOCIAL_AUTH_TUNNISTAMO_SECRET
- [ ] TOKEN_AUTH_AUTHSERVER_URL
- [ ] TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX
- [ ] TUNNISTAMO_API_TOKENS_ENDPOINT

### Private vars (portal.azure.com / Keyvault)

Changes to following:

- [ ] OIDC-RP-CLIENT-SECRET
